language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false

matrix:
  allow_failures:
    - rust: nightly

cache:
  - cargo

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - RUST_BACKTRACE=1